### ISSUE TITLE
Highlights in `<script type="text/x-template">` don't become HTML

### ISSUE THREAD

**Issue by tamago324** [yuezk/vim-js#1]
Thank you for a great plugin.

The highlight when the `<script>` tag type is `text/x-template` is not as expected.
In the above case, I want to highlight HTML instead of JavaScript.

Is this fixable?

![image](https://user-images.githubusercontent.com/16581287/70753604-7f76e200-1d78-11ea-8737-899cacbfdf72.png)

```sh
> gvim.exe -u min_vimrc sample.html
```

min_vimrc

```vim
set encoding=utf-8
scriptencoding utf-8

syntax enable
filetype plugin indent on

set nocompatible

call plug#begin('~/vimfiles/plugged')

Plug 'othree/html5.vim'
Plug 'yuezk/vim-js'

call plug#end()
```

sample.html

```html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <h1>fruits-list</h1> 
    <script type="text/x-template" id="fruits-list">
      <h1>fruits-list</h1>
    </script>
  </body>
</html>
```

**Comment by yuezk** [comment]
I see, will take a look later.

**Comment by tamago324** [comment]
Thanks!

**Comment by yuezk** [comment]
@tamago324 This is an issue from the built-in [html.vim](https://github.com/vim/vim/blob/559b9c68fe550f3af63d42e0838622aab1ceb1b3/runtime/syntax/html.vim#L211) syntax file. It didn't distinct the normal script tag from the script tag with a non-standard type.

The workaround for this issue should be something like this:
```vim
augroup ft_html
	au!
	autocmd FileType html :syn region htmlTemplate matchgroup=htmlScriptTag start=+<script type="text/x-template"\_[^>]*>+ keepend end=+</script\_[^>]*>+ contains=@htmlTop
augroup END

```

You can add it to your vimrc. And it will be highlighted as below.
![DeepinScreenshot_select-area_20191216223734](https://user-images.githubusercontent.com/3297602/70915477-de787780-2054-11ea-88d4-f90a61f88e1a.png)

Note that the content inside the script tag can be highlighted well, but the script itself is not well highlighted.

**Comment by tamago324** [comment]
Thank you for explaining carefully!

A deeper understanding of syntax highlight.
I don't understand matchgroup yet, but I'll investigate more.

Thank you very much!
