### ISSUE TITLE
Incorrect syntax highlighting when specifying return value type

### ISSUE THREAD

**Issue by sudokey** [yuezk/vim-js#10]
```
const x = (): number => {
    const test = 1; // Incorrect syntax highlighting
};
```

**Comment by yuezk** [comment]
@sudokey Thanks for your feedback. It's a bit complex to fix syntax highlight for an arrow function with a return type, but I will try.

Currently, you can use the normal function as a workaround.

```js
const x = function(): number {
    const test = 1; // Incorrect syntax highlighting
};
```

**Comment by yuezk** [comment]
@sudokey After a further investigation, it seems not so complex to fix, addressed in latest code. Welcome to your feedback.
