### ISSUE TITLE
Syntax color problem for a comment inside a complex Flow type

### ISSUE THREAD

**Issue by julienw** [yuezk/vim-js#14]
I've just seen a similar problem to #13, but this time with `'` inside a comment, and the comment itself inside some complex Flow typing:
```js
export type GeckoSamples = {|
  schema:
    | {|
        stack: 0,
        time: 1,
        responsiveness: 2,
      |}
    | {|
        stack: 0,
        time: 1,
        eventDelay: 2,
      |},
  data: Array<
    [
      null | IndexIntoGeckoStackTable,
      Milliseconds, // since profile.meta.startTime
      // milliseconds since the last event was processed in this
      // thread's event loop at the time that the sample was taken
      Milliseconds
    ]
  >,
|};
```
Gives
![Screenshot](https://user-images.githubusercontent.com/454175/96975428-b67e5e00-151a-11eb-922b-d1ea1f34db63.png)
I _think_ the comment itself isn't found as a comment, and that's the real source of the problem here; and this is arguably a complex piece of syntax here :-)

**Comment by julienw** [comment]
After this error, all the syntax in the rest of the file is broken, because the type generic is never closed.

The full file is at https://github.com/firefox-devtools/profiler/blob/ada7782f25ba67c72d5fdd525d2430ab6118f2df/src/types/gecko-profile.js if you're curious.

**Comment by yuezk** [comment]
@julienw Both #13 and #14 should have been fixed now. Please verify it.
