### ISSUE TITLE
Standalone syntax

### ISSUE THREAD

**Issue by 89z** [yuezk/vim-js#18]
If I try to just copy the `syntax/javascript.vim` file, it fails because of this:

https://github.com/yuezk/vim-js/blob/d3f5a53cbc059aba69b6f3bdb9f743750a4e0fa0/syntax/javascript.vim#L288-L291

It would be nice if the file worked on its own, for users who only want the syntax.

**Comment by yuezk** [comment]
@89z I muted the file missing error for `flow.vim` and `jsdoc.vim` in #19. Not sure whether it is your expectation?

**Comment by 89z** [comment]
Yes that is good, thank you!
