### ISSUE TITLE
jsParensError with stage-3 "Class field declarations"

### ISSUE THREAD

**Issue by davidsierradz** [yuezk/vim-js#2]
Sorry if this is out of scope or maybe to soon to implement, for reference look: [tc39/proposal-class-fields: Orthogonally-informed combination of public and private fields proposals](https://github.com/tc39/proposal-class-fields), with a minimal `init.vim`:

```vimscript
call plug#begin('~/.config/nvim/plugged')
Plug 'yuezk/vim-js'
call plug#end()
```

And the following JavaScript file:

```javascript
class Foo {
  foo = async x => {  
    try {
      console.log(x)   
      return x || {}
    } catch (e) {
      console.error(e)
    }
  }
}
```

There are some `jsParensError` syntax errors:

![image](https://user-images.githubusercontent.com/9190258/76801875-8280d480-67a4-11ea-8766-9bf30c12296d.png)

Just letting you know in case you want to check it, maybe we can wait until this gets in a official ES release, although currently is a wide supported feature:

> Babel 7.0+
> Node 12
> Public fields are enabled by default in Chrome 72 / V8 7.2
> Private fields are enabled by default in Chrome 74 / V8 7.4
> Public instance fields are enabled by default in Firefox 69
> Public static fields are enabled in Firefox Nightly 75 as of Febraury 22, 2020
> Public instance fields are shipped behind a flag in Safari Technology Preview 101
> Moddable XS
> QuickJS
> TypeScript 3.8

Thanks!

**Comment by yuezk** [comment]
@davidsierradz It seems to be a flaw caused by the anonymous async function. I have fixed it in the latest code and didn't break my test files. Let me know if you have any questions.
