### ISSUE TITLE
Regex syntax highlighting issue

### ISSUE THREAD

**Issue by davebrace** [yuezk/vim-js#4]
Hello - thank you for making this plugin! Overall it works great. 

However, I've run into a syntax issue with `/` being incorrectly identified as the start of a regex when it is in fact being used as a division operator. Below is a a contrived example - typically I run into this with Prettier formatting lines with the division operator and long variable names.

<img width="298" alt="image" src="https://user-images.githubusercontent.com/212263/76962354-12ca3100-68ed-11ea-97d6-17cc3607708f.png">

Code for reference:

```js
const test = /alskjdf/i;

const math = 5 /
 2;

let thisSyntaxIsBroken;

const asdflkjasdf = 432432 / 23432;

const fixed;
```

**Comment by yuezk** [comment]
Thanks for your feedback, fixed in the latest code.

**Comment by davebrace** [comment]
Thank you for fixing!
