### ISSUE TITLE
comment within flow function type parentheses

### ISSUE THREAD

**Issue by sinap-fb** [yuezk/vim-js#7]
hi, thanks for the plugin.  looks like `//` and `/* */` comments aren't detected when inside of the argument parens for a function flowtype definition
![Screen Shot 2020-03-21 at 7 47 50 PM](https://user-images.githubusercontent.com/58194933/77241288-2b686e80-6bad-11ea-8f33-1908bdfd70ed.png)
Thanks

**Comment by yuezk** [comment]
@sinap-fb Thanks for your feedback, fixed in the latest code.
